### ISSUE TITLE
Clean imports

### ISSUE THREAD

**Issue by arnau** [iwi/linkatos#27]
Internal `import`, right now are mostly in the form of:

```python
import linkatos.parser as parser
```

This can be normalised as:

```python
import parser
```

You only need to specifiy the package `linkatos` when the import happens outside the package.

**Comment by iwi** [comment]
a first attempt didn't work

**Comment by arnau** [comment]
Ok, I read https://docs.python.org/3/reference/import.html.  Apparently in Python 3 you don't do `import parser` but `from linkatos import parser` or to keep it free from `linkatos`, `from . import parser`.

Notice that if you want to get the functions from the module avoiding the `parser` bit, you can do

```python
from .parser import parse_url_message

def f(x):
   parse_url_message(x)
```

**Comment by iwi** [comment]
thx
